- name: Ensure python is installed
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Clone the application repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: "main"

- name: Create the application virtual environment
  command: python3 -m venv {{ venv_dir }}
  args:
    creates: "{{ venv_dir }}/bin/activate"

- name: Install Python dependencies
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"
    virtualenv_python: python3

- name: Create Flask .env file
  template:
    src: flask.env.j2
    dest: "{{ app_dir }}/.env"

- name: Create systemd service for Flask
  template:
    src: flaskapp.service.j2
    dest: /etc/systemd/system/flaskapp.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start Flask service
  service:
    name: flaskapp
    enabled: yes
    state: started
