- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx for Flask
  template:
    src: flaskapp.nginx.conf.j2
    dest: /etc/nginx/sites-available/flaskapp.conf

- name: Enable the new Flask site
  file:
    src: /etc/nginx/sites-available/flaskapp.conf
    dest: /etc/nginx/sites-enabled/flaskapp.conf
    state: link
  notify: restart nginx

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
